### ISSUE TITLE
`<main>': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by theutz** [markgrovs/todo.txt-scripts#1]
When I try to run `todo.sh standup` I get this error:

```
/Users/USERNAME/.todo.actions.d/standup:34:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)`
```

Any ideas about that?

**Comment by markgrovs** [comment]
I'm not sure I don't run todo.txt any longer. You may want to ask the main author: https://github.com/civrot/todo_txt_actions

**Comment by theutz** [comment]
Thanks!

_Michael Utz_
Web Development & Design
http://theutz.com
